plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

description = 'DEKAT Booking - reservation lifecycle'

dependencies {
    api project(':sharedkernel')
    api project(':tenant')
    api project(':customer')
    api project(':catalog')
    api project(':scheduling')
    api project(':staff')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
