plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

description = 'DEKAT Catalog - service & product listings'

dependencies {
    api project(':sharedkernel')
    api project(':tenant')
    api project(':staff')
    api project(':media')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
