import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { adminApi } from '../../lib/api';
import AdminLayout from '../../components/AdminLayout';
import StatusBadge from '../../components/admin/StatusBadge';

interface Plan { id: string; name: string; priceAmount: number; billingCycle: string; maxStaff: number; maxBookingsPerMonth: number; status: string; }
interface Subscription { id: string; tenantId: string; planId: string; status: string; currentPeriodStart: string; currentPeriodEnd: string; }

export default function SubscriptionsPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<'plans' | 'subscriptions'>('plans');
  const { data: plansRes, isLoading: plansLoading } = useQuery({ queryKey: ['admin', 'subscription-plans'], queryFn: () => adminApi.subscriptions.listPlans() });
  const plans = plansRes?.data ?? [];
  const { data: subsRes, isLoading: subsLoading } = useQuery({ queryKey: ['admin', 'subscriptions'], queryFn: () => adminApi.subscriptions.list() });
  const subscriptions = subsRes?.data ?? [];
  const togglePlanMut = useMutation({ mutationFn: ({ planId, status }: { planId: string; status: string }) => adminApi.subscriptions.updatePlan(planId, { status }), onSuccess: () => qc.invalidateQueries({ queryKey: ['admin', 'subscription-plans'] }) });
  const cancelSubMut = useMutation({ mutationFn: (id: string) => adminApi.subscriptions.cancel(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['admin', 'subscriptions'] }) });
  const reactivateSubMut = useMutation({ mutationFn: (id: string) => adminApi.subscriptions.reactivate(id), onSuccess: () => qc.invalidateQueries({ queryKey: ['admin', 'subscriptions'] }) });
  const loading = plansLoading || subsLoading;

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div><h1 className="text-2xl font-bold text-gray-900">Subscription Management</h1><p className="mt-1 text-sm text-gray-500">Kelola paket langganan dan langganan aktif</p></div>
        <div className="flex gap-1 border-b border-gray-200"><button onClick={() => setTab('plans')} className={`px-4 py-2.5 text-sm font-medium transition-colors ${tab === 'plans' ? 'border-b-2 border-primary-600 text-primary-700' : 'text-gray-500 hover:text-gray-700'}`}>Plans</button><button onClick={() => setTab('subscriptions')} className={`px-4 py-2.5 text-sm font-medium transition-colors ${tab === 'subscriptions' ? 'border-b-2 border-primary-600 text-primary-700' : 'text-gray-500 hover:text-gray-700'}`}>Subscriptions</button></div>
        {loading ? <div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-14 animate-pulse rounded-xl bg-gray-100" />)}</div>
        : tab === 'plans' ? <div className="rounded-xl bg-white shadow-sm ring-1 ring-gray-100 overflow-hidden"><table className="w-full"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Cycle</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Max Staff</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Max Bookings/Month</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{plans.map((plan: Plan) => <tr key={plan.id} className="hover:bg-gray-50 transition-colors"><td className="px-4 py-3 text-sm font-medium text-gray-900">{plan.name}</td><td className="px-4 py-3 text-sm text-gray-900">Rp {(plan.priceAmount || 0).toLocaleString()}</td><td className="px-4 py-3 text-sm text-gray-600">{plan.billingCycle}</td><td className="px-4 py-3 text-sm text-gray-600">{plan.maxStaff}</td><td className="px-4 py-3 text-sm text-gray-600">{plan.maxBookingsPerMonth}</td><td className="px-4 py-3 text-sm"><StatusBadge status={plan.status} /></td><td className="px-4 py-3 text-sm"><button onClick={() => togglePlanMut.mutate({ planId: plan.id, status: plan.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' })} className="font-medium text-primary-600 hover:text-primary-800 transition-colors">{plan.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>
        : <div className="rounded-xl bg-white shadow-sm ring-1 ring-gray-100 overflow-hidden"><table className="w-full"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Tenant ID</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Plan</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Period Start</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Period End</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{subscriptions.map((sub: Subscription) => { const plan = plans.find((p: Plan) => p.id === sub.planId); return <tr key={sub.id} className="hover:bg-gray-50 transition-colors"><td className="px-4 py-3 text-sm font-mono text-gray-600">{sub.tenantId?.substring(0, 8)}</td><td className="px-4 py-3 text-sm text-gray-900">{plan?.name || sub.planId?.substring(0, 8)}</td><td className="px-4 py-3 text-sm"><StatusBadge status={sub.status} /></td><td className="px-4 py-3 text-sm text-gray-600">{sub.currentPeriodStart ? new Date(sub.currentPeriodStart).toLocaleDateString('id-ID') : '-'}</td><td className="px-4 py-3 text-sm text-gray-600">{sub.currentPeriodEnd ? new Date(sub.currentPeriodEnd).toLocaleDateString('id-ID') : '-'}</td><td className="px-4 py-3 text-sm space-x-2">{sub.status !== 'CANCELLED' && <button onClick={() => cancelSubMut.mutate(sub.id)} className="font-medium text-red-600 hover:text-red-800 transition-colors">Cancel</button>}{sub.status === 'CANCELLED' && <button onClick={() => reactivateSubMut.mutate(sub.id)} className="font-medium text-green-600 hover:text-green-800 transition-colors">Reactivate</button>}</td></tr>})}{subscriptions.length === 0 && <tr><td colSpan={6} className="px-4 py-12 text-center text-sm text-gray-500">Tidak ada langganan ditemukan</td></tr>}</tbody></table></div>}
      </div>
    </AdminLayout>
  );
}
