plugins {
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'id.dekat'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    set('springDocVersion', '2.5.0')
    set('mapstructVersion', '1.5.5.Final')
    set('springModulithVersion', '1.3.2')
    set('jjwtVersion', '0.12.5')
    set('hypersistenceVersion', '3.16.0')
}

// Common configuration for all subprojects
configure(subprojects) {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'

    repositories {
        mavenCentral()
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.4"
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
        annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

        testCompileOnly 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'

        // Test dependencies
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.security:spring-security-test'
        testImplementation "org.springframework.modulith:spring-modulith-starter-test:${springModulithVersion}"
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
        testImplementation 'org.mockito:mockito-core:5.11.0'
        testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
        testImplementation 'org.assertj:assertj-core:3.24.2'
        testImplementation 'org.testcontainers:junit-jupiter:1.19.7'
        testImplementation 'org.testcontainers:postgresql:1.19.7'
        testImplementation 'com.h2database:h2:2.2.224'
    }
}