rootProject.name = 'platform_backend'

include 'sharedkernel'
include 'identity'
include 'access'
include 'tenant'
include 'staff'
include 'catalog'
include 'scheduling'
include 'booking'
include 'payment'
include 'subscription'
include 'customer'
include 'marketplace'
include 'review'
include 'promotion'
include 'notification'
include 'support'
include 'reporting'
include 'media'
include 'audit'
include 'platformconfig'
include 'api'
