plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

description = 'DEKAT Media - file uploads, images, CDN'

dependencies {
    api project(':sharedkernel')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
