plugins {
    id 'java-library'
}

description = 'DEKAT Support - tickets & chat'

dependencies {
    api project(':sharedkernel')
    api project(':tenant')
    api project(':customer')
    api project(':staff')

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
